### ISSUE TITLE
Could not call npm3 properly

### ISSUE THREAD

**Issue by Z-Clive** [timoxley/npm3#1]
I'm using Windows 10 with npm 2.14.4.

After installed npm3 (`npm install npm3 -g`), and trying to run `npm3` in `cmd`, it fails with:

```
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:849:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at Object.<anonymous> (C:\Users\Clive\AppData\Roaming\npm\node_modules\npm3\bin\index.js:6:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:118:18)
```

**Comment by timoxley** [comment]
Resolved by #2.
